name: Release to NuGet

on:
  workflow_run:
    workflows:
      - Release
    types:
      - completed
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
    - name: Build
      run: dotnet build AikenDoc -c Release
    - name: Test
      run: dotnet test AikenDoc -c Release --no-build
    - name: Get Changelog Entry
      id: changelog_reader
      uses: mindsers/changelog-reader-action@v2
      with:
        path: ./CHANGELOG.md
    - name: Pack nugets
      run: dotnet pack AikenDoc -c Release --no-build --output . /p:Version=${{ steps.changelog_reader.outputs.version }}
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_SECRET}} --source https://api.nuget.org/v3/index.json
