name: Release to NuGet

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
    - name: Build
      run: dotnet build AikenDocument -c Release
    - name: Test
      run: dotnet test AikenDocument -c Release --no-build
    - name: Pack nugets
      run: dotnet pack AikenDocument -c Release --no-build --output . /p:Version=0.5.0
    - name: Push to NuGet
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_SECRET}} --source https://api.nuget.org/v3/index.json
