name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
      - name: Build
        run: dotnet build AikenDocument -c Release
      - name: Test
        run: dotnet test AikenDocument -c Release --no-build
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./CHANGELOG.md
      - name: release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.changelog_reader.outputs.version }}
          tag_name: v${{ steps.changelog_reader.outputs.version }}
          body: ${{ steps.changelog_reader.outputs.changes }}
  NuGet:
    uses: S0Ale/AikenDocument/.github/workflows/main.yml@main
        
