name: Test

on:
  push:
    branches: [ main, master ]
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches: [ main, master ]
    paths:
    - '**.cs'
    - '**.csproj'
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
    
      - name: Build
        run: dotnet build AikenDoc -c Release
      - name: Test
        run: dotnet test AikenDoc -c Release --no-build
